// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using street_foody.Models;

namespace street_foody.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("street_foody.Models.Food", b =>
                {
                    b.Property<string>("FoodID")
                        .HasColumnType("text")
                        .HasColumnName("food_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("EnglishName")
                        .HasColumnType("text")
                        .HasColumnName("english_name");

                    b.Property<string>("FoodCategoryID")
                        .HasColumnType("text")
                        .HasColumnName("food_category_id");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text")
                        .HasColumnName("photo_url");

                    b.Property<double>("Price")
                        .HasColumnType("double precision")
                        .HasColumnName("price");

                    b.Property<string>("VendorID")
                        .HasColumnType("text")
                        .HasColumnName("vendor_id");

                    b.Property<string>("VietnameseName")
                        .HasColumnType("text")
                        .HasColumnName("vietnamese_name");

                    b.HasKey("FoodID")
                        .HasName("pk_food");

                    b.HasIndex("FoodCategoryID")
                        .HasDatabaseName("ix_food_food_category_id");

                    b.HasIndex("VendorID")
                        .HasDatabaseName("ix_food_vendor_id");

                    b.ToTable("food");

                    b.HasData(
                        new
                        {
                            FoodID = "1",
                            EnglishName = "Hu tieu thap cam | Mixed rice noodle soup",
                            FoodCategoryID = "2",
                            Price = 25000.0,
                            VendorID = "1",
                            VietnameseName = "Hủ tiếu thập cẩm"
                        },
                        new
                        {
                            FoodID = "2",
                            EnglishName = "Banh mi thit nguoi | Cold cut",
                            FoodCategoryID = "13",
                            Price = 15000.0,
                            VendorID = "2",
                            VietnameseName = "Bánh mì thịt nguội"
                        },
                        new
                        {
                            FoodID = "3",
                            EnglishName = "Mien | Mixed stir-fried glass noodles",
                            FoodCategoryID = "6",
                            Price = 10000.0,
                            VendorID = "3",
                            VietnameseName = "Miến"
                        },
                        new
                        {
                            FoodID = "4",
                            EnglishName = "Bun | Rice vermicelli",
                            FoodCategoryID = "4",
                            Price = 10000.0,
                            VendorID = "3",
                            VietnameseName = "Bún"
                        },
                        new
                        {
                            FoodID = "5",
                            EnglishName = "Nui xao thap cam | Vietnamese macaroni",
                            FoodCategoryID = "7",
                            Price = 10000.0,
                            VendorID = "3",
                            VietnameseName = "Nui xào thập cẩm"
                        },
                        new
                        {
                            FoodID = "6",
                            EnglishName = "Them mien | Additional mixed stir-fried glass noodles",
                            FoodCategoryID = "6",
                            Price = 3000.0,
                            VendorID = "3",
                            VietnameseName = "Thêm miến"
                        },
                        new
                        {
                            FoodID = "7",
                            EnglishName = "Them Bun | Additional rice vermicelli",
                            FoodCategoryID = "4",
                            Price = 3000.0,
                            VendorID = "3",
                            VietnameseName = "Thêm Bún"
                        },
                        new
                        {
                            FoodID = "8",
                            EnglishName = "Them nui xao thap cam | Additional Vietnamese macaroni",
                            FoodCategoryID = "7",
                            Price = 3000.0,
                            VendorID = "3",
                            VietnameseName = "Thêm nui xào thập cẩm"
                        },
                        new
                        {
                            FoodID = "9",
                            EnglishName = "Xoi man - size vua | Savory sticky rice - medium",
                            FoodCategoryID = "12",
                            Price = 10000.0,
                            VendorID = "4",
                            VietnameseName = "Xôi mặn - size vừa"
                        },
                        new
                        {
                            FoodID = "34",
                            EnglishName = "Xoi man - size lon | Savory sticky rice - large",
                            FoodCategoryID = "12",
                            Price = 15000.0,
                            VendorID = "4",
                            VietnameseName = "Xôi mặn - size lớn"
                        },
                        new
                        {
                            FoodID = "10",
                            EnglishName = "Tra sua | Boba tea",
                            FoodCategoryID = "28",
                            Price = 20000.0,
                            VendorID = "5",
                            VietnameseName = "Trà sữa"
                        },
                        new
                        {
                            FoodID = "11",
                            EnglishName = "Trung cut long đao (10 trứng) | Soft-boiled quail eggs (10ct)",
                            FoodCategoryID = "19",
                            Price = 15000.0,
                            VendorID = "5",
                            VietnameseName = "Trúng cút lòng đào (10 trứng)"
                        },
                        new
                        {
                            FoodID = "12",
                            EnglishName = "Trung ga long dao (2 trứng) | Soft-boiled chicken eggs (2ct)",
                            FoodCategoryID = "19",
                            Price = 14000.0,
                            VendorID = "5",
                            VietnameseName = "Trứng gà lòng đào (2 trứng)"
                        },
                        new
                        {
                            FoodID = "13",
                            EnglishName = "Thap 3 tang combo | 3 story tower combo",
                            FoodCategoryID = "29",
                            Price = 29000.0,
                            VendorID = "5",
                            VietnameseName = "Tháp 3 tầng combo"
                        },
                        new
                        {
                            FoodID = "14",
                            EnglishName = "Bun bo thap cam | Mixed beef vermicelli soup",
                            FoodCategoryID = "4",
                            Price = 35000.0,
                            VendorID = "6",
                            VietnameseName = "Bún bò thập cẩm"
                        },
                        new
                        {
                            FoodID = "15",
                            EnglishName = "Tra sua tran chau, banh flan, pho mai vien | Milk tea with boba, flan cake and cheese ball",
                            FoodCategoryID = "28",
                            Price = 45000.0,
                            VendorID = "7",
                            VietnameseName = "Trà sữa trân châu, bánh flan, phô mai viên"
                        },
                        new
                        {
                            FoodID = "16",
                            EnglishName = "Bun bo thap cam + gio | Mixed beef + pig's trotter vermicelli soup",
                            FoodCategoryID = "4",
                            Price = 45000.0,
                            VendorID = "6",
                            VietnameseName = "Bún bò thập cẩm + giò"
                        },
                        new
                        {
                            FoodID = "17",
                            EnglishName = "Pho mai vien (1 vien) | Cheese ball (1ct)",
                            FoodCategoryID = "30",
                            Price = 2000.0,
                            VendorID = "7",
                            VietnameseName = "Phô mai viên (1 viên)"
                        },
                        new
                        {
                            FoodID = "18",
                            EnglishName = "Xoi 9 mau | 9-color sweet sticky rice",
                            FoodCategoryID = "12",
                            Price = 20000.0,
                            VendorID = "8",
                            VietnameseName = "Xôi 9 màu"
                        },
                        new
                        {
                            FoodID = "19",
                            EnglishName = "Tra sua khong topping | Milk tea without toppings",
                            FoodCategoryID = "28",
                            Price = 17000.0,
                            VendorID = "9",
                            VietnameseName = "Trà sữa không topping"
                        },
                        new
                        {
                            FoodID = "20",
                            EnglishName = "Combos| Combos",
                            FoodCategoryID = "28",
                            Price = 27000.0,
                            VendorID = "9",
                            VietnameseName = "Combos"
                        },
                        new
                        {
                            FoodID = "21",
                            EnglishName = "Tra sua trai cay | Fruit milk tea",
                            FoodCategoryID = "28",
                            Price = 15000.0,
                            VendorID = "9",
                            VietnameseName = "Trà sữa trái cây"
                        },
                        new
                        {
                            FoodID = "22",
                            EnglishName = "Banh trang tron trung cut | Rice paper mix with quail eggs",
                            FoodCategoryID = "19",
                            Price = 15000.0,
                            VendorID = "10",
                            VietnameseName = "Bánh tráng trộn trứng cút"
                        },
                        new
                        {
                            FoodID = "23",
                            EnglishName = "Suong sao thap cam (1 lit.) | Grass jelly mix (1 lit.)",
                            FoodCategoryID = "30",
                            Price = 15000.0,
                            VendorID = "11",
                            VietnameseName = "Sương sáo thập cẩm (1 lit.)"
                        },
                        new
                        {
                            FoodID = "24",
                            EnglishName = "Che thap cam | Sweet gruel mixed combo",
                            FoodCategoryID = "23",
                            Price = 10000.0,
                            VendorID = "11",
                            VietnameseName = "Chè thập cẩm"
                        },
                        new
                        {
                            FoodID = "25",
                            EnglishName = "Coc tai trai cay | Fruit cocktails",
                            FoodCategoryID = "30",
                            Price = 15000.0,
                            VendorID = "11",
                            VietnameseName = "Cốc tai trái cây"
                        },
                        new
                        {
                            FoodID = "26",
                            EnglishName = "Che dau xanh | Sweet green bean gruel",
                            FoodCategoryID = "23",
                            Price = 15000.0,
                            VendorID = "11",
                            VietnameseName = "Chè đậu xanh"
                        },
                        new
                        {
                            FoodID = "27",
                            EnglishName = "Banh mi thit nuong | Banh mi with grilled pork",
                            FoodCategoryID = "13",
                            Price = 22000.0,
                            VendorID = "12",
                            VietnameseName = "Bánh mì thịt nướng"
                        },
                        new
                        {
                            FoodID = "28",
                            EnglishName = "Banh mi thit nuong op la | Banh mi with grilled pork and omelette",
                            FoodCategoryID = "13",
                            Price = 27000.0,
                            VendorID = "12",
                            VietnameseName = "Bánh mì thịt nướng ốp la"
                        },
                        new
                        {
                            FoodID = "29",
                            EnglishName = "Banh mi thit nuong pho mai | Banh mi with grilled prok and cheese",
                            FoodCategoryID = "13",
                            Price = 27000.0,
                            VendorID = "12",
                            VietnameseName = "Bánh mì thịt nướng phô mai"
                        },
                        new
                        {
                            FoodID = "30",
                            EnglishName = "Hu tieu go cha, thit, bo vien | Hu tieu go with fishcake, meat, and beef ball",
                            FoodCategoryID = "2",
                            Price = 20000.0,
                            VendorID = "13",
                            VietnameseName = "Hủ tiếu gõ chả, thịt, bò viên"
                        },
                        new
                        {
                            FoodID = "31",
                            EnglishName = "Bo bia (10 cuốn) | Popiah (10 rolls)",
                            FoodCategoryID = "16",
                            Price = 30000.0,
                            VendorID = "14",
                            VietnameseName = "Bò bía (10 cuốn)"
                        },
                        new
                        {
                            FoodID = "32",
                            EnglishName = "Milk tea (oolong, chocolate, matcha, oreo)",
                            FoodCategoryID = "28",
                            Price = 20000.0,
                            VendorID = "15",
                            VietnameseName = "Trà sữa (oolong, chocolate, matcha, oreo)"
                        },
                        new
                        {
                            FoodID = "33",
                            EnglishName = "Tra trai cay (xoai, đao, tao, vai, dau, kiwi) | Fruit tea (mango, peach, apple, lychee, strawberry, kiwi)",
                            FoodCategoryID = "28",
                            Price = 20000.0,
                            VendorID = "15",
                            VietnameseName = "Trà trái cây (xoài, đào, táo, vải, dâu, kiwi)"
                        },
                        new
                        {
                            FoodID = "35",
                            EnglishName = "Tra sua kem trung | Egg cream milk tea",
                            FoodCategoryID = "28",
                            Price = 25000.0,
                            VendorID = "15",
                            VietnameseName = "Trà sữa kem trứng"
                        },
                        new
                        {
                            FoodID = "36",
                            EnglishName = "Xien que ca/bo/tom: | Skewer (fish/beef/shrimp balls)",
                            FoodCategoryID = "21",
                            Price = 6000.0,
                            VendorID = "15",
                            VietnameseName = "Xiên que cá/bò/tôm:"
                        },
                        new
                        {
                            FoodID = "37",
                            EnglishName = "Hoanh thanh chien (1ct) | Fried wontons (1ct)",
                            FoodCategoryID = "30",
                            Price = 10000.0,
                            VendorID = "15",
                            VietnameseName = "Hoành thánh chiên (1ct)"
                        },
                        new
                        {
                            FoodID = "38",
                            EnglishName = "Khoai tay lac pho mai | Cheese-soaked potato",
                            FoodCategoryID = "30",
                            Price = 20000.0,
                            VendorID = "15",
                            VietnameseName = "Khoai tây lắc phô mai"
                        },
                        new
                        {
                            FoodID = "39",
                            EnglishName = "Banh gao lac pho mai | Cheese-soaked rice cake",
                            FoodCategoryID = "30",
                            Price = 20000.0,
                            VendorID = "15",
                            VietnameseName = "Bánh gạo lắc phô mai"
                        });
                });

            modelBuilder.Entity("street_foody.Models.FoodCategory", b =>
                {
                    b.Property<string>("FoodCategoryID")
                        .HasColumnType("text")
                        .HasColumnName("food_category_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("EnglishName")
                        .HasColumnType("text")
                        .HasColumnName("english_name");

                    b.Property<string>("VietnameseName")
                        .HasColumnType("text")
                        .HasColumnName("vietnamese_name");

                    b.HasKey("FoodCategoryID")
                        .HasName("pk_food_category");

                    b.ToTable("food_category");

                    b.HasData(
                        new
                        {
                            FoodCategoryID = "1",
                            Description = " A soup with rice noodles, herbs, and meat. Pho in Saigon tends to have a clearer broth, and can include bean sprouts, fresh sliced chili, hoisin sauce, and additional herbs. Pho is considered to be Vietnam's national dish.",
                            EnglishName = "Pho | Pho",
                            VietnameseName = "Phở"
                        },
                        new
                        {
                            FoodCategoryID = "2",
                            Description = "This noodle dish can be served with or without broth (dry) and includes pork bones, herbs, and a variety of meats and other ingredients.",
                            EnglishName = "Hu tieu | Rice noodles, or simply hu tieu",
                            VietnameseName = "Hủ tiếu"
                        },
                        new
                        {
                            FoodCategoryID = "3",
                            Description = "Noodles made out of wheat flour or egg noodles. These noodles can be thick or thin, and can be served in soups or dry (without broth).",
                            EnglishName = "Mi | Egg noodles",
                            VietnameseName = "Mì"
                        },
                        new
                        {
                            FoodCategoryID = "4",
                            Description = "These thin rice noodles, also known as rice vermicelli, can be found in soups, served with meats and vegetables, or in goi cuon.",
                            EnglishName = "Bun | Vietnamese rice vermicelli",
                            VietnameseName = "Bún"
                        },
                        new
                        {
                            FoodCategoryID = "5",
                            Description = "Thick tapioca noodles that can be served with a variety of broths and toppings, which can include crab, fish cakes, pork, and more.",
                            EnglishName = "Banh canh | Tapioca noodles, banh canh",
                            VietnameseName = "Bánh canh"
                        },
                        new
                        {
                            FoodCategoryID = "6",
                            Description = "Also known as cellophane or glass noodles, these help make up Vietnamese dishes like mien ga, a chicken soup. Often confused with bun, or rice vermicelli, glass noodles can be distinguished by their clear glass-like appearance when cooked.",
                            EnglishName = "Mien | Cellophane noodles/glass noodles",
                            VietnameseName = "Miến"
                        },
                        new
                        {
                            FoodCategoryID = "7",
                            Description = "These noodles are Vietnamese macaroni, and are often included in Vietnamese chicken and noodle soups.",
                            EnglishName = "Nui | Vietnamese macaroni",
                            VietnameseName = "Nui"
                        },
                        new
                        {
                            FoodCategoryID = "8",
                            Description = "Rice noodle rolls made from thin sheets of fermented rice that are steamed and filled with pork, mushrooms, and shallots.",
                            EnglishName = "Bánh cuốn | Steamed rice rolls, Rice noodle rolls",
                            VietnameseName = "Bánh cuốn"
                        },
                        new
                        {
                            FoodCategoryID = "9",
                            Description = "This dish is made from broken rice grains, and is quite popular in Saigon. It often includes grilled pork ribs, fried egg, scallions, fresh and pickled vegetables, and fish sauce.",
                            EnglishName = "Com tam | Vietnamese broken rice",
                            VietnameseName = "Cơm tấm"
                        },
                        new
                        {
                            FoodCategoryID = "10",
                            Description = "Vietnamese congee, or rice porridge. It can be combined with chicken, duck, or pork and broth, as well as vegetables, and can also be served with youtiao (a type of fried dough).",
                            EnglishName = "Chao | Congee",
                            VietnameseName = "Cháo"
                        },
                        new
                        {
                            FoodCategoryID = "11",
                            Description = "A type of thick, chunky soup made from flavored soup base, egg and tapioca starch. Other typical ingredients include quail eggs, crab meat, pig brain, mushrooms and vegetables. In English, known as egg drop soup.",
                            EnglishName = "Sup | Egg drop soup",
                            VietnameseName = "Súp"
                        },
                        new
                        {
                            FoodCategoryID = "12",
                            Description = "",
                            EnglishName = "Xoi | Sticky rice",
                            VietnameseName = "Xôi"
                        },
                        new
                        {
                            FoodCategoryID = "13",
                            Description = "A sandwich made with a short baguette that often includes pork, cucumber, pickled carrots, cilantro, chili, and mayonnaise, or a wide variety of other ingredients and combinations.",
                            EnglishName = "Banh mi | Vietnamese sandwich",
                            VietnameseName = "Bánh mì"
                        },
                        new
                        {
                            FoodCategoryID = "14",
                            Description = "A round savory bun filled with meat, eggs, and vegetables including onions and mushrooms. Often include Chinese sausage and hard-boiled egg.",
                            EnglishName = "Banh bao | Vietnamese steamed bun",
                            VietnameseName = "Bánh bao"
                        },
                        new
                        {
                            FoodCategoryID = "15",
                            Description = "Originally from China, these can include wontons, dumplings and poststickers and other ball/bun shaped dishes eaten with or without soup. Generally, they are meat balls wrapped inside flour wrappers.",
                            EnglishName = "Diem sam | Dim sum",
                            VietnameseName = "Điểm sấm"
                        },
                        new
                        {
                            FoodCategoryID = "16",
                            Description = "Any Vietnamese traditional food that comes in the form of rolls, e.g. summer rolls, egg rolls, bo bia, .... Wrappers are commonly made from rice papers or betel leaves.",
                            EnglishName = "Cuon | Rolls",
                            VietnameseName = "Cuốn"
                        },
                        new
                        {
                            FoodCategoryID = "17",
                            Description = "These crispy, savory pancakes are made of rice flour, water, and turmeric, fried in a pan and filled with ingredients like pork, prawns, green onion, mung bean, and herbs.",
                            EnglishName = "Pancakes | Crispy pancakes",
                            VietnameseName = "Pancakes"
                        },
                        new
                        {
                            FoodCategoryID = "18",
                            Description = "Rice paper wrappers made from a mixture of rice flour with tapioca starch, water and salt. They are thin and light in texture, and often used in egg rolls and spring rolls.",
                            EnglishName = "Banh trang | Rice paper",
                            VietnameseName = "Bánh tráng"
                        },
                        new
                        {
                            FoodCategoryID = "19",
                            Description = "Eggs (usually from a quail, a duck or a chicken), often boiled and fertilized, or soft-boiled.",
                            EnglishName = "Trung | Eggs",
                            VietnameseName = "Trứng"
                        },
                        new
                        {
                            FoodCategoryID = "20",
                            Description = "Sweet cakes are a type of Vietnamese dessert and come in many varieties. Cakes can often include rice flour and coconut milk, and can feature flavors like banana and cassava, among others.",
                            EnglishName = "Banh ngot | Sweet cakes",
                            VietnameseName = "Bánh ngọt"
                        },
                        new
                        {
                            FoodCategoryID = "21",
                            Description = "Skewered food in Vietnam can include fried fish balls, grilled corn, grilled sausage, and more.",
                            EnglishName = "Xien que | Skewers",
                            VietnameseName = "Xiên que"
                        },
                        new
                        {
                            FoodCategoryID = "22",
                            Description = "",
                            EnglishName = "Trai cay | Trai cay Fruits",
                            VietnameseName = "Trái cây"
                        },
                        new
                        {
                            FoodCategoryID = "23",
                            Description = "Sweet gruel is another Vietnamese dessert, with textures ranging from that of a soup to a pudding. Flavors vary, including fruits and chocolates, and often include coconut milk, rice, and/or tapioca.",
                            EnglishName = "Che | Sweet gruel",
                            VietnameseName = "Chè"
                        },
                        new
                        {
                            FoodCategoryID = "24",
                            Description = "",
                            EnglishName = "Nuoc ep | Juice",
                            VietnameseName = "Nước ép"
                        },
                        new
                        {
                            FoodCategoryID = "25",
                            Description = "",
                            EnglishName = "Nuoc dong chai | Bottled drinks",
                            VietnameseName = "Nước đóng chai"
                        },
                        new
                        {
                            FoodCategoryID = "26",
                            Description = "",
                            EnglishName = "Tra | Tea",
                            VietnameseName = "Trà"
                        },
                        new
                        {
                            FoodCategoryID = "27",
                            Description = "",
                            EnglishName = "Ca phe | Vietnamese coffee",
                            VietnameseName = "Cà phê"
                        },
                        new
                        {
                            FoodCategoryID = "28",
                            Description = "",
                            EnglishName = "Tra sua | Boba tea",
                            VietnameseName = "Trà sữa"
                        },
                        new
                        {
                            FoodCategoryID = "29",
                            Description = "",
                            EnglishName = "Trang mieng | Dessert",
                            VietnameseName = "Tráng miệng"
                        },
                        new
                        {
                            FoodCategoryID = "30",
                            Description = "",
                            EnglishName = "Other | Other",
                            VietnameseName = "Other"
                        });
                });

            modelBuilder.Entity("street_foody.Models.StreetVendor", b =>
                {
                    b.Property<string>("VendorID")
                        .HasColumnType("text")
                        .HasColumnName("vendor_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("EnglishName")
                        .HasColumnType("text")
                        .HasColumnName("english_name");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text")
                        .HasColumnName("photo_url");

                    b.Property<int[]>("PriceRange")
                        .HasColumnType("integer[]")
                        .HasColumnName("price_range");

                    b.Property<int[]>("RatingList")
                        .HasColumnType("integer[]")
                        .HasColumnName("rating_list");

                    b.Property<string>("VendorName")
                        .HasColumnType("text")
                        .HasColumnName("vendor_name");

                    b.Property<string>("VietnameseName")
                        .HasColumnType("text")
                        .HasColumnName("vietnamese_name");

                    b.HasKey("VendorID")
                        .HasName("pk_street_vendor");

                    b.ToTable("street_vendor");

                    b.HasData(
                        new
                        {
                            VendorID = "1",
                            EnglishName = "Hu tieu Tran Binh Trong | Tran Binh Trong rice noodles",
                            PhotoUrl = "https://static.riviu.co/640/image/2020/09/04/bef16221de75b45fea2dd579b5c9a29a_output.jpeg",
                            PriceRange = new[] { 15000, 30000 },
                            RatingList = new[] { 4, 4, 4 },
                            VietnameseName = "Hủ tiếu Trần Bình Trọng"
                        },
                        new
                        {
                            VendorID = "2",
                            EnglishName = "Banh mi Di Loan | Aunty Loan's banh mi",
                            PriceRange = new[] { 15000, 20000 },
                            RatingList = new[] { 5 },
                            VietnameseName = "Bánh mì Dì Loan"
                        },
                        new
                        {
                            VendorID = "3",
                            EnglishName = "Mien xa | Miến xào",
                            PriceRange = new[] { 10000, 15000 },
                            RatingList = new[] { 5 },
                            VietnameseName = "Miến xào"
                        },
                        new
                        {
                            VendorID = "4",
                            EnglishName = "Xoi | Sticky rice",
                            PriceRange = new[] { 10000, 15000 },
                            RatingList = new[] { 3 },
                            VietnameseName = "Xôi"
                        },
                        new
                        {
                            VendorID = "5",
                            EnglishName = "An vat, tra sua đuong Vinh Vien | Vinh Vien St. snacks and boba tea",
                            PhotoUrl = "https://scontent.ffcm1-2.fna.fbcdn.net/v/t1.0-9/156646575_817247045527459_8464517707157016028_n.jpg?_nc_cat=1&ccb=3&_nc_sid=b9115d&_nc_ohc=7qGQxbPz5GIAX94w5F1&_nc_ht=scontent.ffcm1-2.fna&oh=66f3c0a1330121b1100836f404c5ced8&oe=60685917",
                            PriceRange = new[] { 14000, 29000 },
                            RatingList = new int[0],
                            VietnameseName = "Ăn vặt, trà sữa đường Vĩnh Viễn"
                        },
                        new
                        {
                            VendorID = "6",
                            EnglishName = "Bun bo Bau Sen | Bau Sen market beef vermicelli soup",
                            PhotoUrl = "https://scontent.ffcm1-2.fna.fbcdn.net/v/t1.0-9/84698123_1286864361515233_6961019376854106112_n.jpg?_nc_cat=108&ccb=3&_nc_sid=730e14&_nc_ohc=E1KHA4sGlc4AX_ZY4Mn&_nc_ht=scontent.ffcm1-2.fna&oh=8a56d06173f2342f91f7da037f89fff0&oe=60666BCB",
                            PriceRange = new[] { 35000, 45000 },
                            RatingList = new[] { 5 },
                            VietnameseName = "Bún bò Bàu Sen"
                        },
                        new
                        {
                            VendorID = "7",
                            EnglishName = "Tra sua Anva | Anva boba tea",
                            PhotoUrl = "https://scontent.ffcm1-2.fna.fbcdn.net/v/t1.0-9/155165695_240195354407050_2744091707808776661_n.jpg?_nc_cat=101&ccb=3&_nc_sid=8bfeb9&_nc_ohc=05vpqk1kzbAAX9TFzD4&_nc_ht=scontent.ffcm1-2.fna&oh=6b0b19a21677cc60dc3c605d0746e109&oe=606906E4",
                            PriceRange = new[] { 99999999, 99999999 },
                            VietnameseName = "Trà sữa Anva"
                        },
                        new
                        {
                            VendorID = "8",
                            EnglishName = "Xoi ngot chi U | Chubby sis's sweet sticky rice",
                            PhotoUrl = "https://scontent.ffcm1-2.fna.fbcdn.net/v/t1.0-9/155122691_1246898299037777_4391716006726234458_n.jpg?_nc_cat=107&ccb=3&_nc_sid=b9115d&_nc_ohc=Oh-3nRYX_ywAX_XtP7F&_nc_ht=scontent.ffcm1-2.fna&oh=6d0ae3ea925ae24e6cc4fefe7eb8f5ec&oe=606915A1",
                            PriceRange = new[] { 20000, 25000 },
                            VietnameseName = "Xôi ngọt chị Ú"
                        },
                        new
                        {
                            VendorID = "9",
                            EnglishName = "Tiger Tea | Tiger Tea",
                            PhotoUrl = "https://scontent.ffcm1-1.fna.fbcdn.net/v/t1.0-9/155512636_546860506277469_3968119529767571609_o.jpg?_nc_cat=109&ccb=3&_nc_sid=b9115d&_nc_ohc=a11O8kknWEQAX-WDDGL&_nc_ht=scontent.ffcm1-1.fna&oh=2bb5aef40ca9ab14683c771ff074e599&oe=6066F325",
                            PriceRange = new[] { 15000, 40000 },
                            RatingList = new[] { 5 },
                            VietnameseName = "Tiger Tea"
                        },
                        new
                        {
                            VendorID = "10",
                            EnglishName = "Banh trang Ba Ngoai | Grandma's rice paper mix",
                            PhotoUrl = "https://static.riviu.co/960/image/2021/01/23/507d435341a6bf9a8b78f73b2498cff8_output.jpeg",
                            PriceRange = new[] { 15000, 20000 },
                            RatingList = new[] { 5, 5, 5, 4 },
                            VietnameseName = "Bánh tráng Bà Ngoại"
                        },
                        new
                        {
                            VendorID = "11",
                            EnglishName = "Che co Thuy | Aunty Thuy's sweet gruel",
                            PhotoUrl = "https://cdn01.diadiemanuong.com/ddau/999x/undefined-che-co-thuy-cao-dat-0-56b16e9637305080834967437.jpg",
                            PriceRange = new[] { 10000, 15000 },
                            RatingList = new[] { 5, 5, 5, 5 },
                            VietnameseName = "Chè cô Thủy"
                        },
                        new
                        {
                            VendorID = "12",
                            EnglishName = "Banh mi Ba Noi | Grandma's banh mi",
                            PhotoUrl = "https://static.riviu.co/960/image/2020/06/15/f38acd6e2f5fa2c9e3529702ddc1f588_output.jpeg",
                            PriceRange = new[] { 20000, 25000 },
                            RatingList = new[] { 4 },
                            VietnameseName = "Bánh mì Bà Nội"
                        },
                        new
                        {
                            VendorID = "13",
                            EnglishName = "Hu tieu go 20k | Hu tieu go 20k",
                            PhotoUrl = "https://static.riviu.co/960/image/2020/11/23/60cc5128a4dae43cef57378f30e688c0_output.jpeg",
                            PriceRange = new[] { 15000, 20000 },
                            RatingList = new[] { 5 },
                            VietnameseName = "Hủ tiếu gõ 20k"
                        },
                        new
                        {
                            VendorID = "14",
                            EnglishName = "Bo bia 2 ong chu | 2 uncles' popiah",
                            PhotoUrl = "https://static.riviu.co/960/image/2020/12/28/e02c4fae62a8993c43996561df2865a4_output.jpeg",
                            PriceRange = new[] { 30000, 30000 },
                            RatingList = new[] { 5 },
                            VietnameseName = "Bò bía 2 ông chú"
                        },
                        new
                        {
                            VendorID = "15",
                            EnglishName = "Green Box (Gibi) | Green Box (Gibi)",
                            PhotoUrl = "https://static.riviu.co/960/image/2020/12/04/67fabbc325dd84ba17fdc0e6e63978e9_output.jpeg",
                            PriceRange = new[] { 5000, 40000 },
                            RatingList = new[] { 3, 4, 4 },
                            VietnameseName = "Green Box (Gibi)"
                        });
                });

            modelBuilder.Entity("street_foody.Models.VendorHours", b =>
                {
                    b.Property<string>("VendorHoursID")
                        .HasColumnType("text")
                        .HasColumnName("vendor_hours_id");

                    b.Property<DateTime[]>("Fri")
                        .HasColumnType("timestamp without time zone[]")
                        .HasColumnName("fri");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<DateTime[]>("Mon")
                        .HasColumnType("timestamp without time zone[]")
                        .HasColumnName("mon");

                    b.Property<DateTime[]>("Sat")
                        .HasColumnType("timestamp without time zone[]")
                        .HasColumnName("sat");

                    b.Property<DateTime[]>("Sun")
                        .HasColumnType("timestamp without time zone[]")
                        .HasColumnName("sun");

                    b.Property<DateTime[]>("Thu")
                        .HasColumnType("timestamp without time zone[]")
                        .HasColumnName("thu");

                    b.Property<DateTime[]>("Tue")
                        .HasColumnType("timestamp without time zone[]")
                        .HasColumnName("tue");

                    b.Property<string>("VendorID")
                        .HasColumnType("text")
                        .HasColumnName("vendor_id");

                    b.Property<DateTime[]>("Wed")
                        .HasColumnType("timestamp without time zone[]")
                        .HasColumnName("wed");

                    b.HasKey("VendorHoursID")
                        .HasName("pk_vendor_hours");

                    b.HasIndex("VendorID")
                        .HasDatabaseName("ix_vendor_hours_vendor_id");

                    b.ToTable("vendor_hours");

                    b.HasData(
                        new
                        {
                            VendorHoursID = "1",
                            Fri = new[] { new DateTime(2021, 3, 12, 15, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2021, 3, 12, 21, 0, 0, 0, DateTimeKind.Unspecified) },
                            Location = "359 Tran Binh Trong, Ward 1, District 10, HCMC",
                            Mon = new[] { new DateTime(2021, 3, 12, 15, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2021, 3, 12, 21, 0, 0, 0, DateTimeKind.Unspecified) },
                            Sat = new[] { new DateTime(2021, 3, 12, 15, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2021, 3, 12, 21, 0, 0, 0, DateTimeKind.Unspecified) },
                            Sun = new[] { new DateTime(2021, 3, 12, 15, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2021, 3, 12, 21, 0, 0, 0, DateTimeKind.Unspecified) },
                            Thu = new[] { new DateTime(2021, 3, 12, 15, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2021, 3, 12, 21, 0, 0, 0, DateTimeKind.Unspecified) },
                            Tue = new[] { new DateTime(2021, 3, 12, 15, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2021, 3, 12, 21, 0, 0, 0, DateTimeKind.Unspecified) },
                            VendorID = "1",
                            Wed = new[] { new DateTime(2021, 3, 12, 15, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2021, 3, 12, 21, 0, 0, 0, DateTimeKind.Unspecified) }
                        },
                        new
                        {
                            VendorHoursID = "2",
                            Fri = new[] { new DateTime(2021, 3, 12, 5, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2021, 3, 12, 11, 0, 0, 0, DateTimeKind.Unspecified) },
                            Location = "15 D5 St., Ward 25, Binh Thanh District, HCMC",
                            Mon = new[] { new DateTime(2021, 3, 12, 5, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2021, 3, 12, 11, 0, 0, 0, DateTimeKind.Unspecified) },
                            Sat = new[] { new DateTime(2021, 3, 12, 5, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2021, 3, 12, 11, 0, 0, 0, DateTimeKind.Unspecified) },
                            Tue = new[] { new DateTime(2021, 3, 12, 5, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2021, 3, 12, 11, 0, 0, 0, DateTimeKind.Unspecified) },
                            VendorID = "2",
                            Wed = new[] { new DateTime(2021, 3, 12, 5, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2021, 3, 12, 11, 0, 0, 0, DateTimeKind.Unspecified) }
                        },
                        new
                        {
                            VendorHoursID = "3",
                            Fri = new[] { new DateTime(2021, 3, 12, 10, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2021, 3, 12, 12, 0, 0, 0, DateTimeKind.Unspecified) },
                            Location = "10-12 Dinh Tien Hoang St., Ben Nghe Ward, District 1, HCMC",
                            Mon = new[] { new DateTime(2021, 3, 12, 10, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2021, 3, 12, 12, 0, 0, 0, DateTimeKind.Unspecified) },
                            Tue = new[] { new DateTime(2021, 3, 12, 10, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2021, 3, 12, 12, 0, 0, 0, DateTimeKind.Unspecified) },
                            VendorID = "3",
                            Wed = new[] { new DateTime(2021, 3, 12, 10, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2021, 3, 12, 12, 0, 0, 0, DateTimeKind.Unspecified) }
                        },
                        new
                        {
                            VendorHoursID = "4",
                            Fri = new[] { new DateTime(2021, 3, 12, 6, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2021, 3, 12, 8, 0, 0, 0, DateTimeKind.Unspecified) },
                            Location = "217 Hong Bang, Ward 1, District 5, HCMC",
                            Mon = new[] { new DateTime(2021, 3, 12, 6, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2021, 3, 12, 8, 0, 0, 0, DateTimeKind.Unspecified) },
                            Tue = new[] { new DateTime(2021, 3, 12, 6, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2021, 3, 12, 8, 0, 0, 0, DateTimeKind.Unspecified) },
                            VendorID = "4",
                            Wed = new[] { new DateTime(2021, 3, 12, 6, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2021, 3, 12, 8, 0, 0, 0, DateTimeKind.Unspecified) }
                        },
                        new
                        {
                            VendorHoursID = "5",
                            Fri = new[] { new DateTime(2021, 3, 12, 9, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2021, 3, 12, 22, 0, 0, 0, DateTimeKind.Unspecified) },
                            Location = "82 Vinh Vien, Ward 2, District 10, HCMC",
                            Mon = new[] { new DateTime(2021, 3, 12, 9, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2021, 3, 12, 22, 0, 0, 0, DateTimeKind.Unspecified) },
                            Sat = new[] { new DateTime(2021, 3, 12, 9, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2021, 3, 12, 22, 0, 0, 0, DateTimeKind.Unspecified) },
                            Sun = new[] { new DateTime(2021, 3, 12, 9, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2021, 3, 12, 22, 0, 0, 0, DateTimeKind.Unspecified) },
                            Thu = new[] { new DateTime(2021, 3, 12, 9, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2021, 3, 12, 22, 0, 0, 0, DateTimeKind.Unspecified) },
                            Tue = new[] { new DateTime(2021, 3, 12, 9, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2021, 3, 12, 22, 0, 0, 0, DateTimeKind.Unspecified) },
                            VendorID = "5",
                            Wed = new[] { new DateTime(2021, 3, 12, 9, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2021, 3, 12, 22, 0, 0, 0, DateTimeKind.Unspecified) }
                        },
                        new
                        {
                            VendorHoursID = "6",
                            Fri = new[] { new DateTime(2021, 3, 12, 17, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2021, 3, 12, 23, 59, 0, 0, DateTimeKind.Unspecified) },
                            Location = "138 Nguyen Trai, Ward 3, District 5",
                            Mon = new[] { new DateTime(2021, 3, 12, 17, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2021, 3, 12, 23, 59, 0, 0, DateTimeKind.Unspecified) },
                            Sat = new[] { new DateTime(2021, 3, 12, 17, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2021, 3, 12, 11, 59, 0, 0, DateTimeKind.Unspecified) },
                            Sun = new[] { new DateTime(2021, 3, 12, 17, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2021, 3, 12, 23, 59, 0, 0, DateTimeKind.Unspecified) },
                            Thu = new[] { new DateTime(2021, 3, 12, 17, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2021, 3, 12, 23, 59, 0, 0, DateTimeKind.Unspecified) },
                            Tue = new[] { new DateTime(2021, 3, 12, 17, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2021, 3, 12, 23, 59, 0, 0, DateTimeKind.Unspecified) },
                            VendorID = "6",
                            Wed = new[] { new DateTime(2021, 3, 12, 17, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2021, 3, 12, 23, 59, 0, 0, DateTimeKind.Unspecified) }
                        },
                        new
                        {
                            VendorHoursID = "7",
                            Fri = new[] { new DateTime(2021, 3, 12, 11, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2021, 3, 12, 21, 0, 0, 0, DateTimeKind.Unspecified) },
                            Location = "267 Pham Van Chi, Ward 3, District 6",
                            Mon = new[] { new DateTime(2021, 3, 12, 11, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2021, 3, 12, 21, 0, 0, 0, DateTimeKind.Unspecified) },
                            Sat = new[] { new DateTime(2021, 3, 12, 11, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2021, 3, 12, 21, 0, 0, 0, DateTimeKind.Unspecified) },
                            Sun = new[] { new DateTime(2021, 3, 12, 11, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2021, 3, 12, 21, 0, 0, 0, DateTimeKind.Unspecified) },
                            Thu = new[] { new DateTime(2021, 3, 12, 11, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2021, 3, 12, 21, 0, 0, 0, DateTimeKind.Unspecified) },
                            Tue = new[] { new DateTime(2021, 3, 12, 11, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2021, 3, 12, 21, 0, 0, 0, DateTimeKind.Unspecified) },
                            VendorID = "7",
                            Wed = new[] { new DateTime(2021, 3, 12, 11, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2021, 3, 12, 21, 0, 0, 0, DateTimeKind.Unspecified) }
                        },
                        new
                        {
                            VendorHoursID = "8",
                            Fri = new[] { new DateTime(2021, 3, 12, 15, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2021, 3, 12, 23, 59, 0, 0, DateTimeKind.Unspecified) },
                            Location = "8 Phan Van Han, Ward 19, Binh Thanh District",
                            Mon = new[] { new DateTime(2021, 3, 12, 15, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2021, 3, 12, 23, 59, 0, 0, DateTimeKind.Unspecified) },
                            Sat = new[] { new DateTime(2021, 3, 12, 15, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2021, 3, 12, 23, 59, 0, 0, DateTimeKind.Unspecified) },
                            Sun = new[] { new DateTime(2021, 3, 12, 15, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2021, 3, 12, 23, 59, 0, 0, DateTimeKind.Unspecified) },
                            Thu = new[] { new DateTime(2021, 3, 12, 15, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2021, 3, 12, 23, 59, 0, 0, DateTimeKind.Unspecified) },
                            Tue = new[] { new DateTime(2021, 3, 12, 15, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2021, 3, 12, 23, 59, 0, 0, DateTimeKind.Unspecified) },
                            VendorID = "8",
                            Wed = new[] { new DateTime(2021, 3, 12, 15, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2021, 3, 12, 23, 59, 0, 0, DateTimeKind.Unspecified) }
                        },
                        new
                        {
                            VendorHoursID = "9",
                            Fri = new[] { new DateTime(2021, 3, 12, 18, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2021, 3, 12, 22, 0, 0, 0, DateTimeKind.Unspecified) },
                            Location = "27 Thanh Da, Ward 27, Binh Thanh District",
                            Mon = new[] { new DateTime(2021, 3, 12, 18, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2021, 3, 12, 22, 0, 0, 0, DateTimeKind.Unspecified) },
                            Sat = new[] { new DateTime(2021, 3, 12, 18, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2021, 3, 12, 22, 0, 0, 0, DateTimeKind.Unspecified) },
                            Sun = new[] { new DateTime(2021, 3, 12, 18, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2021, 3, 12, 22, 0, 0, 0, DateTimeKind.Unspecified) },
                            Thu = new[] { new DateTime(2021, 3, 12, 18, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2021, 3, 12, 22, 0, 0, 0, DateTimeKind.Unspecified) },
                            Tue = new[] { new DateTime(2021, 3, 12, 18, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2021, 3, 12, 22, 0, 0, 0, DateTimeKind.Unspecified) },
                            VendorID = "9",
                            Wed = new[] { new DateTime(2021, 3, 12, 18, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2021, 3, 12, 22, 0, 0, 0, DateTimeKind.Unspecified) }
                        },
                        new
                        {
                            VendorHoursID = "10",
                            Fri = new[] { new DateTime(2021, 3, 12, 17, 30, 0, 0, DateTimeKind.Unspecified), new DateTime(2021, 3, 12, 22, 0, 0, 0, DateTimeKind.Unspecified) },
                            Location = "623/20 CMT8, P.15, Q.10",
                            Mon = new[] { new DateTime(2021, 3, 12, 17, 30, 0, 0, DateTimeKind.Unspecified), new DateTime(2021, 3, 12, 22, 0, 0, 0, DateTimeKind.Unspecified) },
                            Sat = new[] { new DateTime(2021, 3, 12, 17, 30, 0, 0, DateTimeKind.Unspecified), new DateTime(2021, 3, 12, 22, 0, 0, 0, DateTimeKind.Unspecified) },
                            Sun = new[] { new DateTime(2021, 3, 12, 17, 30, 0, 0, DateTimeKind.Unspecified), new DateTime(2021, 3, 12, 22, 0, 0, 0, DateTimeKind.Unspecified) },
                            Thu = new[] { new DateTime(2021, 3, 12, 17, 30, 0, 0, DateTimeKind.Unspecified), new DateTime(2021, 3, 12, 22, 0, 0, 0, DateTimeKind.Unspecified) },
                            Tue = new[] { new DateTime(2021, 3, 12, 17, 30, 0, 0, DateTimeKind.Unspecified), new DateTime(2021, 3, 12, 22, 0, 0, 0, DateTimeKind.Unspecified) },
                            VendorID = "10",
                            Wed = new[] { new DateTime(2021, 3, 12, 17, 30, 0, 0, DateTimeKind.Unspecified), new DateTime(2021, 3, 12, 22, 0, 0, 0, DateTimeKind.Unspecified) }
                        },
                        new
                        {
                            VendorHoursID = "11",
                            Fri = new[] { new DateTime(2021, 3, 12, 11, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2021, 3, 12, 17, 0, 0, 0, DateTimeKind.Unspecified) },
                            Location = "897/29 Tran Hung Dao, Ward 01, District 5, HCMC",
                            Mon = new[] { new DateTime(2021, 3, 12, 11, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2021, 3, 12, 17, 0, 0, 0, DateTimeKind.Unspecified) },
                            Sat = new[] { new DateTime(2021, 3, 12, 11, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2021, 3, 12, 17, 0, 0, 0, DateTimeKind.Unspecified) },
                            Sun = new[] { new DateTime(2021, 3, 12, 11, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2021, 3, 12, 17, 0, 0, 0, DateTimeKind.Unspecified) },
                            Thu = new[] { new DateTime(2021, 3, 12, 11, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2021, 3, 12, 17, 0, 0, 0, DateTimeKind.Unspecified) },
                            Tue = new[] { new DateTime(2021, 3, 12, 11, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2021, 3, 12, 17, 0, 0, 0, DateTimeKind.Unspecified) },
                            VendorID = "11",
                            Wed = new[] { new DateTime(2021, 3, 12, 11, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2021, 3, 12, 17, 0, 0, 0, DateTimeKind.Unspecified) }
                        },
                        new
                        {
                            VendorHoursID = "12",
                            Fri = new[] { new DateTime(2021, 3, 12, 6, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2021, 3, 12, 21, 0, 0, 0, DateTimeKind.Unspecified) },
                            Location = "246/55A Hoa Hung, Ward 13, District 10",
                            Mon = new[] { new DateTime(2021, 3, 12, 6, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2021, 3, 12, 21, 0, 0, 0, DateTimeKind.Unspecified) },
                            Sat = new[] { new DateTime(2021, 3, 12, 6, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2021, 3, 12, 21, 0, 0, 0, DateTimeKind.Unspecified) },
                            Sun = new[] { new DateTime(2021, 3, 12, 6, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2021, 3, 12, 21, 0, 0, 0, DateTimeKind.Unspecified) },
                            Thu = new[] { new DateTime(2021, 3, 12, 6, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2021, 3, 12, 21, 0, 0, 0, DateTimeKind.Unspecified) },
                            Tue = new[] { new DateTime(2021, 3, 12, 6, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2021, 3, 12, 21, 0, 0, 0, DateTimeKind.Unspecified) },
                            VendorID = "12",
                            Wed = new[] { new DateTime(2021, 3, 12, 6, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2021, 3, 12, 21, 0, 0, 0, DateTimeKind.Unspecified) }
                        },
                        new
                        {
                            VendorHoursID = "13",
                            Fri = new[] { new DateTime(2021, 3, 12, 18, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2021, 3, 12, 22, 0, 0, 0, DateTimeKind.Unspecified) },
                            Location = "48 Kha Van Can St., Binh Chanh Ward, Thu Duc District",
                            Mon = new[] { new DateTime(2021, 3, 12, 18, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2021, 3, 12, 22, 0, 0, 0, DateTimeKind.Unspecified) },
                            Sat = new[] { new DateTime(2021, 3, 12, 18, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2021, 3, 12, 22, 0, 0, 0, DateTimeKind.Unspecified) },
                            Sun = new[] { new DateTime(2021, 3, 12, 18, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2021, 3, 12, 22, 0, 0, 0, DateTimeKind.Unspecified) },
                            Thu = new[] { new DateTime(2021, 3, 12, 18, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2021, 3, 12, 22, 0, 0, 0, DateTimeKind.Unspecified) },
                            Tue = new[] { new DateTime(2021, 3, 12, 18, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2021, 3, 12, 22, 0, 0, 0, DateTimeKind.Unspecified) },
                            VendorID = "13",
                            Wed = new[] { new DateTime(2021, 3, 12, 18, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2021, 3, 12, 22, 0, 0, 0, DateTimeKind.Unspecified) }
                        },
                        new
                        {
                            VendorHoursID = "14",
                            Fri = new[] { new DateTime(2021, 3, 12, 17, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2021, 3, 12, 22, 0, 0, 0, DateTimeKind.Unspecified) },
                            Location = "Le Van Tam Park",
                            Mon = new[] { new DateTime(2021, 3, 12, 17, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2021, 3, 12, 22, 0, 0, 0, DateTimeKind.Unspecified) },
                            Sat = new[] { new DateTime(2021, 3, 12, 17, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2021, 3, 12, 22, 0, 0, 0, DateTimeKind.Unspecified) },
                            Sun = new[] { new DateTime(2021, 3, 12, 17, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2021, 3, 12, 22, 0, 0, 0, DateTimeKind.Unspecified) },
                            Thu = new[] { new DateTime(2021, 3, 12, 17, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2021, 3, 12, 22, 0, 0, 0, DateTimeKind.Unspecified) },
                            Tue = new[] { new DateTime(2021, 3, 12, 17, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2021, 3, 12, 22, 0, 0, 0, DateTimeKind.Unspecified) },
                            VendorID = "14",
                            Wed = new[] { new DateTime(2021, 3, 12, 17, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2021, 3, 12, 22, 0, 0, 0, DateTimeKind.Unspecified) }
                        },
                        new
                        {
                            VendorHoursID = "15",
                            Fri = new[] { new DateTime(2021, 3, 12, 12, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2021, 3, 12, 23, 0, 0, 0, DateTimeKind.Unspecified) },
                            Location = "38 Phạm Ngọc Thạch, P.6, Q.3, HCMC",
                            Mon = new[] { new DateTime(2021, 3, 12, 12, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2021, 3, 12, 23, 0, 0, 0, DateTimeKind.Unspecified) },
                            Sat = new[] { new DateTime(2021, 3, 12, 12, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2021, 3, 12, 23, 0, 0, 0, DateTimeKind.Unspecified) },
                            Sun = new[] { new DateTime(2021, 3, 12, 12, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2021, 3, 12, 23, 0, 0, 0, DateTimeKind.Unspecified) },
                            Thu = new[] { new DateTime(2021, 3, 12, 12, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2021, 3, 12, 23, 0, 0, 0, DateTimeKind.Unspecified) },
                            Tue = new[] { new DateTime(2021, 3, 12, 12, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2021, 3, 12, 23, 0, 0, 0, DateTimeKind.Unspecified) },
                            VendorID = "15",
                            Wed = new[] { new DateTime(2021, 3, 12, 12, 0, 0, 0, DateTimeKind.Unspecified), new DateTime(2021, 3, 12, 23, 0, 0, 0, DateTimeKind.Unspecified) }
                        });
                });

            modelBuilder.Entity("street_foody.Models.Food", b =>
                {
                    b.HasOne("street_foody.Models.FoodCategory", "FoodCategory")
                        .WithMany("Foods")
                        .HasForeignKey("FoodCategoryID")
                        .HasConstraintName("fk_food_food_category_food_category_id");

                    b.HasOne("street_foody.Models.StreetVendor", "Vendor")
                        .WithMany("Foods")
                        .HasForeignKey("VendorID")
                        .HasConstraintName("fk_food_street_vendor_vendor_id");

                    b.Navigation("FoodCategory");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("street_foody.Models.VendorHours", b =>
                {
                    b.HasOne("street_foody.Models.StreetVendor", "Vendor")
                        .WithMany("VendorHours")
                        .HasForeignKey("VendorID")
                        .HasConstraintName("fk_vendor_hours_street_vendor_vendor_id");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("street_foody.Models.FoodCategory", b =>
                {
                    b.Navigation("Foods");
                });

            modelBuilder.Entity("street_foody.Models.StreetVendor", b =>
                {
                    b.Navigation("Foods");

                    b.Navigation("VendorHours");
                });
#pragma warning restore 612, 618
        }
    }
}
